//mysql
//LOAD DATA,LOCAL,REPLACE,IGNORE,FIELDS TERMINATED BY,FILEDS TERMINATED BY,FIELDS ENCLOSED BY,FIELDS TERMINATED BY,FIELDS ENCLOSED BY,LINES TERMINATED BY
// ./import.txt 

LOAD DATA INFILE '/tmp/import.txt' INTO TABLE foo
FILES TERMINATED BY ',' OPTIONALLY ENCLOSED BY '*'
LINES TERMINATED BY '\n'

---

