//MINUS
//INTERSECT

SELECT * FROM foo UNION SELECT * FROM bar

SELECT * FROM foo UNION SELECT * FROM bar
  UNION SELECT * FROM bar2

SELECT * FROM foo UNION ALL SLECT * FROM bar

SELECT a,b FROM foo UNION SELECT c,d,e FROM bar

SELECT a,b,NULL FROM foo UNION SELECT c,d,e FROM bar

SELECT a,b FROM foo UNION SELECT c,d FROM bar ORDER BY 1

(SELECT a FROM foo ORDER BY a) UNION
(SELECT a FROM bar ORDER BY a)



