//INITCAP
//UPPER

SELECT a,INITCAP(a) FROM foo

//FROM DUAL,SYSIBM SYSDUMMY1 fnc only
SELECT CURRENT_TIMESTAMP                       //psgl,mysql
SELECT CURRENT_TIMESTAMP FROM DUAL             //oracle
SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1 //db2


---


