//LAST_VALUE
//FIRST_VALUE
//SUM OVER

SELECT income, LAST_VALUE(income) OVER((ORDER BY income DESC)
  RANGE BETWEEN UNBOUNDED PERCEDING AND UNBOUNDED FOOLLOWING)
  FROM staff ORDER BY income DESC



---


