//SUM OVER
//AGV
//SUM

//OVER
SELECT age,SUM(age) OVER(ORDER BY age) FROM staff
  ORDER BY age


//PARTITION BY
SELECT sex,age,SUM(age) OVER(PARTITION BY sex
  ORDER BY age) FROM staff ORDER BY sex,age

//ROWS RANGE
//ROWS UNBOUNDED PRECEDING
SELECT age,SUM(age) OVER(ORDER BY age ROWS UNBOUNDED
  PRECEDING) FROM staff ORDER BY age
//RANGE
//RANGE BETWEEN CURRENT ROW AND UNBOUNDEDFOLLOWING
SELECT age,SUM(age) OVER(ORDER BY age RANGE BETWEEN
  CURRENT ROW AND UNBOUNDED FOLLOWING) FROM staff
  ORDER BY age
//RANGE BETWEEN 10 PERCEDING AND 10 FOLLOWING
SELECT age,SUM(age) OVER(ORDER BY age RANGE BETWEEN
  10 PRECEDING AND 10 FOLLOWING) FROM staff OVER BY age
//SUM(SUM(age))
SELECT sex,SUM(age),SUM(SUM(age)) OVER(ORDER BY SUM(age)
  ROWS UNBOUNDED PRECEDING) FROM staff GROUP BY sex
  ORDER BY SUM(age)

//AVG  
SELECT AVG(value) OVER(ORDER BY DATE ROWS 4 PRECEDING)
  FROM price

//
//value 値
//attributes 属性















---

