//TRUNC
//DATE_TRUNC
//TO_CHAR
//ROUND

SELECT a,TRUNC(a) FROM foo
SELECT a,TRUNC(a,1) FROM foo
SELECT TO_CHAR(a, 'YY-MM-DD HH24:MI'),
  TO_CHAR(TRUNC(a), 'YY-MM-DD HH24:MI') FROM foo
SELECT TO_CHAR(a, 'YY-MM=DD HH24:MI'),
  TO_CHAR(TRUNC(a,'HH'),'YY-MM-DD HH24:MI') FROM foo


