//DECLARE CURSOR
//FOR

//oracle
//DECLARE IS
DECLARE
  CURSOR cursor_name IS SELECT a FROM foo;
BEGIN
END;
//sql
DECLARE cursor_name CURSOR FOR SELECT a FROM foo


//mysql
//DECLARE CURSOR
//CURSOR FOR
CREATE PROCEDURE test_cursor() LANGUAGE SQL
BEGIN
  DECLARE cursor_name CURSOR FOR SELECT a FROM foo;
END

//psgl
//DECLARE CURSOR FOR
//cursor_name CURSOR FOR SELECT
//FETCH OPEN CLOSE
CREATE OR REPLACE FUNCTION test_cursor() RETURNS void
  AS $$
DECLARE
  cursor_name CURSOR FOR SELECT a FROM foo;
BEGIN
END;
$$ LANGUAGE 'plpgsql';

---


