//DECLARE HANDER
//mysql DECLARE HANDER EXIT UNDO CONTINUE ROLLBACK UNDO ATOMIC condition SQLSTATE '02000' SQLEXCEPTION SQLWARNING NOT FOUND DECLARE 
/*
 00000 //SQLSTATE
 SQLWARNING
 NOT FOUND
 SQLEXCEPTION
 */

//mysql FETCH SQLSTATE '02000'
CREATE PROCEDURE test_handler() LANGUAGE SQL
BEGIN
  DECLARE i INTEGER;
  DECLARE flg INTEGER DEFAULT 1;
  DECLARE cur CURSOR FOR SELECT a FROM foo;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET
    flg = 0;
  OPEN cur;
  fetch_loop: LOOP
    FETCH cur INTO i;
    IF flg = 0 THEN LEAVE fetch_loop; END IF;
  END LOOP;
  CLOSE cur;
END


//db2 not_found NULL '700002'
CREATE PROCEDURE test_handler2() LANGUAGE SQL
BEGIN
  DECLARE i INTEGER;
  DECLARE flg INTEGER DEFAULT 1;
  DECLARE not_found CONDITION FOR SQLSTATE '020000';
  DECLARE is_null CONDITION FOR SQLSTATE '70002';
  DECLARE cur CURSOR FOR SELECT a FROM foo;
  DECLARE CONTINUE HANDLER FOR not_found SET flg = 0;
  DECLARE CONTINUE HANDLER FOR is_null SET flg - 0;
  OPEN cur;
  fetch_loop: LOOP
    FETCH cur INTO i;
    IF i IS NULL THEN SIGNAL SQLSTATE '700002'; END IF;
    IF flg = 0 THEN LEAVE fetch_loop; END IF;
  END LOOP;
  CLOSE cur;
END



















---


