CREATE FUNCTION f_foo(INTEGER) RETURNS INTEGER AS $$
BEGIN
  IF $1 = 0 THEN
	RAISE EXCEPTION 'PARAMS %', $1;
  END IF;
  RETURN 100/$1;
EXCEPTION
  WHEN raise_exception THEN
    RAISE NOTICE 'ERR %', SQLERPM;
  RETURN 0;
END;$$ LANGUAGE 'plpgsql';

