//SIGNAL
//mysql

//SET MESSAGE_TEXT SIGNAL '70001' condition SQLSTATE params(IN a INTEGER) a = 0 
CREATE PROCEDURE p_foo(IN a INTEGER) LANGUAGE SQL
BEGIN
  IF a = 0 THEN
    SIGNAL SQLSTATE '70001'
      SET MESSAGE_TEXT = 'PRAMS 0';
  END IF;
END


---


