//ORDER BY

//ASC DESC
SELECT * FROM foo ORDER BY a ASC
SELECT * FROM foo ORDER BY a DESC

//NULLSELECT * FROM foo ORDER BY DESC NULLS LAST

//psgl
SELECT * FROM foo ORDER BY a DESC NULLS LAST

//ORDER BY
SELECT a,b FROM foo ORDER BY 2
SELECT a,c * b FROM foo ORDER BY 2


//COLLATE
SELECT * FROM foo ORDER BY a COLLATE Japanese_BIN
ALTER SESSION SET NLS_SORT='JAPANESE_M_CI'


---




