//REPLACE
//INSERT
//mysql,sqlite

//INSERT REPLACE UPSERT
REPLACE INTO foo(a,b,c) VALUES(3,'yyy',400)

//UPDATE REPLACE
REPLACE INTO foo SET a=3,b='xxx',c=100

//INSERT ON DUPLICATE KEY UPDATE UPSERT
INSERT INTO foo VALUES(3, 'zzz', 500)
  ON DUPLICATE KEY UPDATE b='zzz', c=500




