//SELECT INTO
//CREATE TABLE AS
//psgl

SELECT * INTO new_foo FROM foo

SELECT a,SUM(b) AS sumb INTO new_foo FROM foo GROUP BY a

//SAVE
//SELECT INTO
SELECT * INTO bar FROM foo

//CREATE TABLE AS oracle
CREATE TABLE bar UNRECOVERABLE AS SELECT * FROM foo

//CREATE TABLE AS SELECT INTO
CREATE TABLE bar AS (SELECT * FROM foo)
  DATA INITIALLY DEFERRED REFRESH DEFERRED
REFRESH TABLE bar

----



