//SUBQUERY

//SELECT MAX(b) FROM bar
SELECT * FROM foo WHERE a = (SELECT MAX(b) FROM bar)

//SELECT SELECT
maxvalue = SELECT MAX(b) FROM bar
SELECT * FROM foo WHERE a = maxvalue

//SELECT SELECT
SELECT * FROM foo WHERE a = (SELECT MAX(b) FROM bar WHERE bar.c = foo.c)

//EXISTS NOT EXSISTS
SELECT * FROM foo WHERE EXISTS (SELECT * FROM bar WHERE bar.a = foo.a)
SELECT * FROM foo WHERE EXISTS (SELECT * FROM bar WHERE foo.a = bar.a)

//SELECT
SELECT (SELECT COUNT(*) FROM foo), (SELECT COUNT(*) FROM bar)

//FROM
SELECT * FROM (SELECT a,b FROM bar) AS SUBQ



//ROWNUM oracle
SELECT * FROM foo WHERE ROWNUM <= 3
SELECT * FROM (SELECT * FROM foo ORDER BY a WHERE ROWNUM <= 3)

---



