//WITH SELF QUERY

WITH td(NNO, PNO, LVL) AS(
  SELECT NODE_NO, PARENT_NO, 0
    FROM TREE_DATA WHERE PARENT_NO IS NULL
  UNION ALL
  SELECT TD2.NODE_NO, TD2.PARENT_NO, td.LVL + 1
    FROM td INNER JOIN TREE_DATA TD2
      ON td.NNO = TD2.PARENT_NO
)
SELECT * FROM td

----




