//ALTER TABLE
//psgl, mysql

ALTER TABLE foo ADD COLUMN c INTEGER
ALTER TABLE foo DROP COLUMN c
ALTER TABLE foo ALTER c SET DEFAULT 0

ALTER TABLE foo ADD CONSTRAINT pkey PRIMARY KEY(a, b)

ALTER TABLE foo ADD CONSTRAINT fkey FOREIGN KEY(a)
  REFERENCES bar(b)

ALTER TABLE foo DROP CONSTRAINT pkey

ALTER TABLE foo DROP DROP PRIMARY KEY

ALTER TABLE foo RENAME c TO new_c
ALTER TABLE foo CHANGE c new_c VARCHAR(30)

ALTER TABLE foo RENAME TO bar
ALTER TABLE foo RENAME AS bar


//COLUMN c INTEGER TABLE foo
ALTER TABLE foo ADD (c INTEGER)
ALTER TABLE foo ADD c INTEGER
ALTER TABLE foo ADD COLUMN c INTEGER

//COLUMN c DELETE
ALTER TABLE foo DROP(c)
ALTER TABLE foo DROP COLUMN c

//MODIFY ALTER
ALTER TABLE foo MODIFY (c VARCHAR2(30))
ALTER TABLE foo ALTER c SET DATA TYPE VARCHAR(20)
ALTER TABLE foo ALTER c SET DEFAULT 0

//PRIMARY KEY
ALTER TABLE foo ADD CONSTRAINT pkey PRIMARY KEY(a,b)

//FOREIGN KEY
ALTER TABLE foo ADD CONSTRAINT fkey FOREIGN KEY(a)
  REFERENCES bar(b)

//DROP CONSTRAINT
ALTER TABLE foo DROP CONSTRAINT pkey
ALTER TABLE foo DROP PRIMARY KEY

//RENAME CHANGE
ALTER TABLE foo RENAME COLUMN c new_c
ALTER TABLE foo RENAME c TO new_c
ALTER TABLE foo CHANGE c new_c VARCHAR(10)

//RENAME TO
ALTER TABLE foo RENAME TO bar
ALTER TABLE foo RENAME AS bar

----



