//CREATE INDEX
//CREATE CLUSTER
//CLUSTER


CREATE INDEX idx ON foo(a)
//CREATE UNIQUE INDEX
CREATE UNIQUE INDEX idx ON foo(a)

//func_name UPPER
CREATE INDEX idx ON foo(UPPER(b))

//CLUSTER CREATE CLUSTERED INDEX
CREATE INDEX idx ON CLUSTER cls_foo
CREATE CLUSTERED INDEX idx ON foo(a)
CREATE INDEX idx ON foo(a) CLUSTER

//SCHEMABINDING INCLUDE
CREATE UNIQUE INDEX idx ON foo(a) INCLUDE(b,c)

//USING
CREATE INDEX idx ON foo USING HASH (a)
CREATE INDEX idx USING HASH ON foo(a)




//psgl
CREATE INDEX idx ON foo(UPPER(b))

//psgl,mysql
CREATE INDEX idx ON foo foo USING HASH (a)
CREATE INDEX idx USING HASH ON foo(a)

----







