//CREATE PROCEDURE

//PARAMS
//CREATE FUNCTION


//oracle CREATE OR REPLACE PROCEDURE
CREATE OR REPLACE PROCEDURE p_foo IS
BEGIN INSERT INTO foo VALUES(SYSDATE); END;

//sql CREATE PROCEDURE AS
CREATE PROCEDURE p_foo AS
  INSERT INTO foo VALUES(GETDATE())
//db2 CREATE PROCEDURE LANGUAGE
CREATE PROCEDURE p_foo() LANGUAGE SQL
  INSERT INTO foo VALUES(CURRENT TIMESTAMP)

---




