//psgl
GRANT ALL ON DATABASE dbfoo To tky

GRANT ALL ON SCHEMA schemafoo TO tky

GRANT ALL ON foo TO tky

GRANT ALL ON SEQUENCE f_foo TO tky

GRANT ALL ON FUNCTION f_foo() TO tky

//mysql
GRANT ALL PRIVILEGES ON *. * TO tky@localhost
FLUSH PRIVILEGES

GRANT ALL PRIVILEGES ON *. * TO ""@localhost
FLUSH PRIVILEGES

GRANT USAGE ON *. * TO tky
FLUSH PRIVILEGES

GRANT USAGE ON *. * TO foo IDENTIFIED BY 'newpasswd'
FLUSH PRIVILEGES

USE mysql
DELETE FROM user WHERE user = ''
FLUSH PRIVILEGES

//REVOKE


